### ISSUE TITLE
Proxy setting is hardcoded for Jersy JAXRS Implementation

### ISSUE THREAD

**Issue by pendula95** [SK-EID/smart-id-java-client#22]
With current implementation proxy settings will only work with Jersy JAXRS provider.
Provide a way to pass configuration to SmartIdClient that will work with all implementations of JAXRS. 
Issue is that Proxy is not specified by JAXRS, instead maybe it would be better to provide a way to pass Client to SmartIdClient.
With current implementation any ClientConfig settings can not be used on WildFly or Jboss.

**Comment by aasaru** [comment]
@pendula95 could you please verify if https://github.com/SK-EID/smart-id-java-client/pull/28 solves your problem. Thanks!

**Comment by pendula95** [comment]
Yes this solves the issue but there is an error. I already commented [https://github.com/SK-EID/smart-id-java-client/pull/28#discussion_r327518625](error)

**Comment by aasaru** [comment]
Thanks @pendula95 for taking time to test it and also for tracking down a bug.
The bug is now fixed (https://github.com/SK-EID/smart-id-java-client/pull/28/commits/45d2d3d479e8a07cf9dc41e259a5cd09dc5d86dd) and the PR can be merged.
