### ISSUE TITLE
Expose SSLContext

### ISSUE THREAD

**Issue by martinpaljak** [SK-EID/smart-id-java-client#3]
The only way to specify a custom SSLContext with trust manager seems to be through ClientBuilder, which is hidden by the Smart-ID API.

To be able to do pinning (required by the security doc!) it should be possible to add a custom context, maybe via `client.setSSLContext()` or something similar

**Comment by jalukse** [comment]
https://github.com/SK-EID/smart-id-java-client/blob/master/CHANGELOG.md#15---2019-11-12
