### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by angryziber** [SK-EID/smart-id-java-client#63]
Easy to get rid of:
* commons-io - only one class is used from it in only 1 other class: FileUtils, probably most users don't need it
* commons-codec - uses DigestUtils in 1 place, which can be replaced with 3 lines of plain Java code
* commons-lang3 - only 3 methods are used and they have respective analogs in Java standard library

Harder:
* jersey and related stuff - too bad such a heavy library is used to just send some http requests. Java has URLConnection and HttpClient built-in
* etc

Why get rid of dependencies?
To avoid bloating apps and Log4j-like problems in the future.

**Comment by jalukse** [comment]
#66 merged
