### ISSUE TITLE
"Signature length not correct: got 512 but was expecting 256" using DEMO environment

### ISSUE THREAD

**Issue by p14n** [SK-EID/smart-id-java-client#75]
I'm using the demo RP and test accounts as documented here https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#demo-parameters

But when validating the response I get:

2022-11-17 16:55:47,561 DEBUG [ee.sk.smartid.AuthenticationResponseValidator] (executor-thread-3) Error verifying signer's certificate: CN="TESTNUMBER,QUALIFIED OK1", SERIALNUMBER=PNOEE-30303039914, GIVENNAME=QUALIFIED OK1, SURNAME=TESTNUMBER, C=EE against CA certificate: CN=sid.demo.sk.ee, O=SK ID Solutions AS, L=Tallinn, C=EE: java.security.SignatureException: Signature length not correct: got 512 but was expecting 256

Is there a way of controlling the sig length?

Thanks

**Comment by jalukse** [comment]
please provide info how hash is generated. In authentication by default SHA512 is used when using method _generateRandomHash()_, sample [#authenticating-with-semantics-identifier](https://github.com/SK-EID/smart-id-java-client#authenticating-with-semantics-identifier)
In that example hash type can be controlled with:
`generateRandomHash(HashType.SHA256)`

Based on error you get I think you have a problem with missing CA certificates. By default this library includes only production certificate chain. Please look into [#how-to-use-it-against-demo-environment](https://github.com/SK-EID/smart-id-java-client/wiki/Using-demo-environment-for-testing#how-to-use-it-against-demo-environment )

**Comment by p14n** [comment]
That's really helpful, thank you - I was using the wrong certificate (from https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#demo-parameters).  All working now.
